# rabbitmq 消费端配置
spring:
  rabbitmq:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        # 限流
        prefetch: 1
    host: "47.92.249.250"
#    host: "192.168.199.199"
    port: 5672
    username: "admin"
    password: "123456"
    virtual-host: "/"
    connection-timeout: 15000

#mybatis:
#  configuration: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.renewable.terminal.pojo


spring.datasource:
  #  url: jdbc:mysql://47.92.249.250:3306/gateway_origin?characterEncoding=utf-8
  url: jdbc:mysql://localhost:3306/gateway_origin?characterEncoding=utf-8&&useSSL=false
  #  username: root
  username: renewable
  password: 123
  driver-class-name: com.mysql.jdbc.Driver
  platform: mysql

#  type: com.alibaba.druid.pool.DruidDataSource
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大\
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000


# logger
logging:
  file: logs/terminal.log
info:
  name: infoname

# server
server:
  port: 8050